import { Shield, Mail } from "lucide-react";

export default function CopyrightPage() {
  const year = new Date().getFullYear();

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-center gap-3 mb-10">
        <div className="w-10 h-10 rounded-xl bg-indigo-100 dark:bg-indigo-950 text-indigo-600 dark:text-indigo-400 flex items-center justify-center">
          <Shield className="w-5 h-5" />
        </div>
        <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white">
          Copyright & Legal
        </h1>
      </div>

      <div className="space-y-8 text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
        {/* Ownership */}
        <section className="rounded-2xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-6">
          <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">
            Ownership
          </h2>
          <p>
            ResumeIQ is developed and owned by <strong className="text-gray-900 dark:text-white">Bablou</strong>. All
            rights reserved. © {year} ResumeIQ.
          </p>
          <p className="mt-2">
            The name "ResumeIQ", the application interface, design, and all associated
            intellectual property are the exclusive property of the developer.
          </p>
        </section>

        {/* Usage restrictions */}
        <section className="rounded-2xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-6">
          <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">
            Usage Restrictions
          </h2>
          <ul className="list-disc list-inside space-y-2">
            <li>
              You may not copy, reproduce, redistribute, or resell any part of this
              application without prior written permission from the owner.
            </li>
            <li>
              The AI-generated analysis is for informational and personal use only.
              It does not constitute professional HR or career advice.
            </li>
            <li>
              Automated scraping, bulk analysis requests, or API abuse is strictly
              prohibited.
            </li>
            <li>
              Any derivative works based on ResumeIQ&apos;s design or codebase require
              explicit written consent.
            </li>
          </ul>
        </section>

        {/* Third-party services */}
        <section className="rounded-2xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-6">
          <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">
            Third-Party Services
          </h2>
          <p>
            ResumeIQ uses the following third-party services, each governed by their
            own terms:
          </p>
          <ul className="mt-2 list-disc list-inside space-y-1">
            <li>
              <strong className="text-gray-800 dark:text-gray-200">Google Gemini API</strong> — AI
              analysis engine. Governed by Google&apos;s AI usage policies.
            </li>
            <li>
              <strong className="text-gray-800 dark:text-gray-200">Firebase Firestore</strong> — Optional
              analysis history storage. Governed by Google Firebase terms.
            </li>
          </ul>
          <p className="mt-3">
            Resume content is processed by the Gemini API per your request and is not
            retained by ResumeIQ. Please review Google&apos;s data handling policies for
            details on API data use.
          </p>
        </section>

        {/* Disclaimer */}
        <section className="rounded-2xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-6">
          <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3">
            Disclaimer
          </h2>
          <p>
            The ATS scores and resume reviews provided by ResumeIQ are generated by AI
            and are for guidance purposes only. ResumeIQ makes no guarantees of job
            placement, interview success, or accurate representation of any particular
            employer&apos;s ATS system. Results may vary.
          </p>
        </section>

        {/* Contact */}
        <section className="rounded-2xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 p-6">
          <h2 className="text-base font-semibold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
            <Mail className="w-4 h-4" />
            Contact
          </h2>
          <p>
            For copyright inquiries, permissions, or legal matters, please reach out
            at:{" "}
            <a
              href="mailto:your-email@example.com"
              className="text-indigo-600 dark:text-indigo-400 hover:underline"
            >
              your-email@example.com
            </a>
          </p>
        </section>

        <p className="text-xs text-gray-400 text-center pt-4">
          Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long" })}
        </p>
      </div>
    </div>
  );
}
